### ISSUE TITLE
Support for Mullvad sock5 proxies

### ISSUE THREAD

**Issue by JanAxelJonsson** [nitrohorse/mullvad-connectivity-checker#1]
Ni

It would be nice if you could add support for on/off Mullvad sock5 proxy (kill-switch)
https://mullvad.net/sv/guides/socks5-proxy/

This gives some benefits:

1. improving the killswitch
2. making it more difficult to detect OpenVPN usage

It would be good if the status icon changed depending on if socks5 is on or off.

Nice work!
/ Jan

**Comment by nitrohorse** [comment]
Thanks for the idea, @JanAxelJonsson, I'll look into it. :+1:

**Comment by nitrohorse** [comment]
@JanAxelJonsson try out [v1.2+](https://addons.mozilla.org/en-US/firefox/addon/mullvad-connectivity-checker/versions/?page=1#version-1.3); this issue is hopefully mitigated.
